#!/bin/bash

colorful_echo()
{
	  local code="\033["
		case "$1" in
					red    ) color="${code}1;31m";;
					green  ) color="${code}1;32m";;
					yellow ) color="${code}1;33m";;
					blue   ) color="${code}1;34m";;
					purple ) color="${code}1;35m";;
					cyan   ) color="${code}1;36m";;
					gray   ) color="${code}0;37m";;
					*) local text="$1"
		esac
		[ -z "$text" ] && local text="$color$2${code}0m"
		echo -ne "$text"
}

TMP_FILE=`mktemp`
colorful_echo cyan "Checking commit message spelling...\n"

commit_msg=$(cat "${1:?Missing commit message file}")

echo "${commit_msg}" > "${TMP_FILE}"

# Allows me to read user input below, assigns stdin to keyboard
exec < /dev/tty

# I'm assuming you have a aspell (spell checker) installed on your system
# invoke aspell and check for typos
/usr/bin/aspell check "${TMP_FILE}"

COMMIT_MSG_NEW=$(cat $TMP_FILE )

if [[ "$COMMIT_MSG_NEW" != "$commit_msg" ]]; then
	colorful_echo gray "Found few typos in original message: "
	colorful_echo red "\"${commit_msg}\"\n"
	colorful_echo gray "Fixed commit message: "
	colorful_echo cyan "\"${COMMIT_MSG_NEW}\"\n"
	commit_msg=${COMMIT_MSG_NEW}
fi

exit 0
