#!/bin/zsh

colorful_echo() 
{
	  local code="\033["
		case "$1" in
					red    ) color="${code}1;31m";;
					green  ) color="${code}1;32m";;
					yellow ) color="${code}1;33m";;
					blue   ) color="${code}1;34m";;
					purple ) color="${code}1;35m";;
					cyan   ) color="${code}1;36m";;
					gray   ) color="${code}0;37m";;
					*) local text="$1"
		esac
		[ -z "$text" ] && local text="$color$2${code}0m"
		echo -e "$text"
}

# Running make only in context of swithiching branches
# and not in case of restoring working tree files.
# so the flag moved_branch indicating whether the checkout was a branch checkout 
# (changing branches, flag=1). 

# TODO: Should remove leftovers from mondator output:
# rm -rf src/blazemeter/Model/Base

moved_branch=$3

if [ $moved_branch -eq 1 ]
then
	new_branch_name=`git branch | grep \* | cut -d ' ' -f2`
	colorful_echo yellow "You have moved to branch:\n${new_branch_name}\nrunning make..."
	make
fi
