#!/bin/zsh

# This hook is called on each push to github (remote repository),
# in case you plan to open a pull request, you should mention this in the last
# commit message with either the string 'PR' or 'Pull Request' (case insensitive).
# this way you will avoid wasting your time on travis (Travis CI).
# You will be notified that the whole tests will get invoked locally before the actual push.

colorful_echo() 
{
	  local code="\033["
		case "$1" in
					red    ) color="${code}1;31m";;
					green  ) color="${code}1;32m";;
					yellow ) color="${code}1;33m";;
					blue   ) color="${code}1;34m";;
					purple ) color="${code}1;35m";;
					cyan   ) color="${code}1;36m";;
					gray   ) color="${code}0;37m";;
					*) local text="$1"
		esac
		[ -z "$text" ] && local text="$color$2${code}0m"
		echo -e "$text"
}


keywords_before_smart_push='PR\|Pull Request'

git_last_commit=`git log -1`

if (echo $git_last_commit | grep -ic $keywords_before_smart_push ) ; then
    colorful_echo  cyan "Before running pull request,"
    colorful_echo  cyan "Will run make all tests, do you wish to run tests? (y/n)"

    read -q ans

    echo ""
    if [ "$ans" = 'y' ] ; then
    	# Executing a script which brings up Redis and Mongo.
    	zsh ~/useful-scripts/unit-test-environment.zsh
    	
    	colorful_echo yellow "Running all tests"
    	make all test
    else 
    	colorful_echo yellow "NO need to run tests"
    fi
fi


exit 0